name: Eastern European Research home page
description: "Eastern Europe Research is part of the Aleksanteri Institute, Finnish Centre for Russian and Eastern European Studies, affiliated with the University of Helsinki"
markdown: redcarpet
redcarpet:
  extensions: ["tables"]
highlighter: false


authors:
  emma:
    display_name: Emma Hakala
  kati:
    display_name: Katalin Miklossy
  mikko:
    display_name: Mikko Palonkorpi
